## Problem Statement

Objective: melakukan sentimen analysis dari review pembeli menjadi sentimen Positif atau Negatif.
Target/label: Positif/Negative
Batasan/asumsi: Hanya ada 2 label sebagai output dari sentimen analysis dari setiap review pembeli.

## 1. Load Library

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from google import genai  # sesuaikan dengan library Gemini API yang digunakan
from google.genai import types
import os

## 2. Load Dataset

In [3]:
df = pd.read_csv("../data/customer_reviews_sentiment.csv")
df.head()

,review_id,product_name,review_text,sentiment
0,1,Kemeja Flanel,Pelayanan lambat dan tidak responsif saat diko...,negatif
1,2,Case HP,"Puas banget belanja disini, proses cepat dan b...",positif
2,3,Rice Cooker,"Terima kasih seller, barangnya awet dan sesuai...",positif
3,4,Case HP,Warna produk berbeda jauh dari foto di listing.,negatif
4,5,Headset Bluetooth,"Terima kasih seller, barangnya awet dan sesuai...",positif

## 3. Setup Training Data Set

In [4]:
X = df['review_text']
y = df['sentiment']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print('Train size:', len(X_train))
print('Test size:', len(X_test))

Train size: 160
Test size: 40

## 4 Model Klasik (Scikit-leard)

### 4.1 Feature Vectorization

In [5]:
vectorizer = TfidfVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

### 4.2 Train the Model

In [6]:
clf = LogisticRegression()
clf.fit(X_train_vec, y_train)

LogisticRegression()

### 4.3 Prediksi menggunakan Test Set

In [8]:
y_pred_classic = clf.predict(X_test_vec)
y_pred_classic

array(['negatif', 'positif', 'positif', 'positif', 'negatif', 'negatif',
       'positif', 'positif', 'negatif', 'negatif', 'positif', 'negatif',
       'positif', 'positif', 'negatif', 'positif', 'negatif', 'positif',
       'negatif', 'negatif', 'positif', 'negatif', 'positif', 'positif',
       'positif', 'positif', 'positif', 'positif', 'positif', 'negatif',
       'positif', 'negatif', 'positif', 'negatif', 'negatif', 'negatif',
       'negatif', 'negatif', 'positif', 'positif'], dtype=object)

## 5. Menggunakan Model LLM - API GEMINI

In [46]:
or_api_key=os.environ.get('OPENROUTER_API_KEY')

In [97]:
import requests
import json

model = "google/gemini-3.8-flash"

def classify_sentiment_llm_OR(review_text):
    prompt = f'''Klasifikasikan sentimen ulasan berikut sebagai "positif" atau "negatif".
Jawab hanya dengan satu kata: positif atau negatif.

Ulasan: "{review_text}"
Sentimen:'''
    response = requests.post(
        url="https://openrouter.ai/api/v1/chat/completions",
        headers={
            "Authorization": f"Bearer {or_api_key}",
            "HTTP-Referer": "<YOUR_SITE_URL>", # Optional. Site URL for rankings on openrouter.ai.
            "X-OpenRouter-Title": "<YOUR_SITE_NAME>", # Optional. Site title for rankings on openrouter.ai.
            },
        data=json.dumps({
            "model": f"{model}",
            "messages": [
                {
                  "role": "user",
                  "content": f"{prompt}"
                }]
        })
    )
    return response.text.strip().lower()

In [71]:
y_pred_llm = []
for review in X_test:
    pred = classify_sentiment_llm_OR(review)
    y_pred_llm.append(pred)

In [72]:
y_pred_llm

['{"id":"gen-1790397426-l8eirkiuh7vjkegl7s4h","object":"chat.completion","created":1790397426,"model":"google/gemini-3.8-flash","provider":"google","system_fingerprint":null,"service_tier":"provisioned","choices":[{"index":0,"logprobs":null,"finish_reason":"stop","native_finish_reason":"stop","message":{"role":"assistant","content":"negatif","refusal":null,"reasoning":"**classifying sentiment**\\n\\nmy analysis of the provided indonesian phrase, \\"barang tidak berfungsi sama sekali begitu diterima,\\" leads me to classify its sentiment as negative. the core of the message clearly indicates a product that was non-functional upon arrival, which is unequivocally a negative experience.\\n\\n","reasoning_details":[{"type":"reasoning.text","text":"**classifying sentiment**\\n\\nmy analysis of the provided indonesian phrase, \\"barang tidak berfungsi sama sekali begitu diterima,\\" leads me to classify its sentiment as negative. the core of the message clearly indicates a product that was non-functional upon arrival, which is unequivocally a negative experience.\\n\\n","format":"google-gemini-v1","index":0}]}}],"usage":{"prompt_tokens":48,"completion_tokens":163,"total_tokens":211,"cost":0.00064725,"is_byok":false,"prompt_tokens_details":{"cached_tokens":0,"cache_write_tokens":0,"audio_tokens":0,"video_tokens":0},"cost_details":{"upstream_inference_cost":0.00064725,"upstream_inference_prompt_cost":0.000036,"upstream_inference_completions_cost":0.00061125},"completion_tokens_details":{"reasoning_tokens":161,"image_tokens":0,"audio_tokens":0}}}',
 '{"id":"gen-1790397431-8okici1yfmckeryf8zr8","object":"chat.completion","created":1790397431,"model":"google/gemini-3.8-flash","provider":"google","system_fingerprint":null,"service_tier":"default","choices":[{"index":0,"logprobs":null,"finish_reason":"stop","native_finish_reason":"stop","message":{"role":"assistant","content":"positif","refusal":null,"reasoning":"**determining sentiment**\\n\\nmy current focus is on classifying customer feedback. i\'ve analyzed a recent piece of text and am determining if its sentiment leans positive or negative based on the language used.\\n\\n","reasoning_details":[{"type":"reasoning.text","text":"**determining sentiment**\\n\\nmy current focus is on classifying customer feedback. i\'ve analyzed a recent piece of text and am determining if its sentiment leans positive or negative based on the language used.\\n\\n","format":"google-gemini-v1","index":0}]}}],"usage":{"prompt_tokens":54,"completion_tokens":159,"total_tokens":213,"cost":0.00063675,"is_byok":false,"prompt_tokens_details":{"cached_tokens":0,"cache_write_tokens":0,"audio_tokens":0,"video_tokens":0},"cost_details":{"upstream_inference_cost":0.00063675,"upstream_inference_prompt_cost":0.0000405,"upstream_inference_completions_cost":0.00059625},"completion_tokens_details":{"reasoning_tokens":157,"image_tokens":0,"audio_tokens":0}}}',
 '{"id":"gen-1790397436-tgy3zkjc0ftnevezskvd","object":"chat.completion","created":1790397436,"model":"google/gemini-3.8-flash","provider":"google","system_fingerprint":null,"service_tier":"default","choices":[{"index":0,"logprobs":null,"finish_reason":"stop","native_finish_reason":"stop","message":{"role":"assistant","content":"positif","refusal":null,"reasoning":"**classifying sentiment**\\n\\nmy current focus is on accurately categorizing the emotional tone of user feedback. i\'ve just processed a statement expressing strong approval, which i\'ve confidently labeled as positive.\\n\\n","reasoning_details":[{"type":"reasoning.text","text":"**classifying sentiment**\\n\\nmy current focus is on accurately categorizing the emotional tone of user feedback. i\'ve just processed a statement expressing strong approval, which i\'ve confidently labeled as positive.\\n\\n","format":"google-gemini-v1","index":0}]}}],"usage":{"prompt_tokens":51,"completion_tokens":174,"total_tokens":225,"cost":0.00069075,"is_byok":false,"prompt_tokens_details":{"cached_tokens":0,"cache_write_tokens":0,"audio_tokens":0,"video_tokens":0},"cost_details":{"upstream_inference_cost":0.00069075,"upstream_inference_prompt_cost":0.00003825,"upstream_inference_completions_cost":0.0006525},"completion_tokens_details":{"reasoning_tokens":172,"image_tokens":0,"audio_tokens":0}}}',
 '{"id":"gen-1790397439-ps1khsr2zudpku8wnhyy","object":"chat.completion","created":1790397439,"model":"google/gemini-3.8-flash","provider":"google","system_fingerprint":null,"service_tier":"provisioned","choices":[{"index":0,"logprobs":null,"finish_reason":"stop","native_finish_reason":"stop","message":{"role":"assistant","content":"positif","refusal":null,"reasoning":"**classifying sentiment accurately**\\n\\ni\'m focusing on determining whether the user\'s feedback leans positive or negative. the current review expresses strong satisfaction, indicating a positive sentiment. my current approach is to identify keywords and phrases that signify approval or disapproval to make a definitive, single-word classification.\\n\\n","reasoning_details":[{"type":"reasoning.text","text":"**classifying sentiment accurately**\\n\\ni\'m focusing on determining whether the user\'s feedback leans positive or negative. the current review expresses strong satisfaction, indicating a positive sentiment. my current approach is to identify keywords and phrases that signify approval or disapproval to make a definitive, single-word classification.\\n\\n","format":"google-gemini-v1","index":0}]}}],"usage":{"prompt_tokens":51,"completion_tokens":192,"total_tokens":243,"cost":0.00075825,"is_byok":false,"prompt_tokens_details":{"cached_tokens":0,"cache_write_tokens":0,"audio_tokens":0,"video_tokens":0},"cost_details":{"upstream_inference_cost":0.00075825,"upstream_inference_prompt_cost":0.00003825,"upstream_inference_completions_cost":0.00072},"completion_tokens_details":{"reasoning_tokens":190,"image_tokens":0,"audio_tokens":0}}}',
 '{"id":"gen-1790397443-zecwkjltp0qdiv46sylc","object":"chat.completion","created":1790397443,"model":"google/gemini-3.8-flash","provider":"google","system_fingerprint":null,"service_tier":"default","choices":[{"index":0,"logprobs":null,"finish_reason":"stop","native_finish_reason":"stop","message":{"role":"assistant","content":"negatif","refusal":null,"reasoning":"**classifying sentiment now**\\n\\ni\'m focusing on discerning whether user feedback leans positive or negative. my current task involves analyzing specific phrases, like \\"ukuran tidak sesuai, terlalu kecil dari yang dipesan,\\" to determine the overall sentiment and provide a one-word classification.\\n\\n","reasoning_details":[{"type":"reasoning.text","text":"**classifying sentiment now**\\n\\ni\'m focusing on discerning whether user feedback leans positive or negative. my current task involves analyzing specific phrases, like \\"ukuran tidak sesuai, terlalu kecil dari yang dipesan,\\" to determine the overall sentiment and provide a one-word classification.\\n\\n","format":"google-gemini-v1","index":0}]}}],"usage":{"prompt_tokens":51,"completion_tokens":180,"total_tokens":231,"cost":0.00071325,"is_byok":false,"prompt_tokens_details":{"cached_tokens":0,"cache_write_tokens":0,"audio_tokens":0,"video_tokens":0},"cost_details":{"upstream_inference_cost":0.00071325,"upstream_inference_prompt_cost":0.00003825,"upstream_inference_completions_cost":0.000675},"completion_tokens_details":{"reasoning_tokens":178,"image_tokens":0,"audio_tokens":0}}}',
 '{"id":"gen-1790397447-7ti230jrtzk9d0egnzvt","object":"chat.completion","created":1790397447,"model":"google/gemini-3.8-flash","provider":"google","system_fingerprint":null,"service_tier":"provisioned","choices":[{"index":0,"logprobs":null,"finish_reason":"stop","native_finish_reason":"stop","message":{"role":"assistant","content":"negatif","refusal":null,"reasoning":"**classifying sentiment**\\n\\nmy analysis of the provided text leads me to classify its sentiment as \'negatif\'. the phrase \\"jauh dari ekspektasi\\" strongly indicates dissatisfaction, despite the mention of \\"mahal\\" (expensive).\\n\\n","reasoning_details":[{"type":"reasoning.text","text":"**classifying sentiment**\\n\\nmy analysis of the provided text leads me to classify its sentiment as \'negatif\'. the phrase \\"jauh dari ekspektasi\\" strongly indicates dissatisfaction, despite the mention of \\"mahal\\" (expensive).\\n\\n","format":"google-gemini-v1","index":0}]}}],"usage":{"prompt_tokens":52,"completion_tokens":184,"total_tokens":236,"cost":0.000729,"is_byok":false,"prompt_tokens_details":{"cached_tokens":0,"cache_write_tokens":0,"audio_tokens":0,"video_tokens":0},"cost_details":{"upstream_inference_cost":0.000729,"upstream_inference_prompt_cost":0.000039,"upstream_inference_completions_cost":0.00069},"completion_tokens_details":{"reasoning_tokens":182,"image_tokens":0,"audio_tokens":0}}}',
 '{"id":"gen-1790397449-abztej8lunktsgntu788","object":"chat.completion","created":1790397449,"model":"google/gemini-3.8-flash","provider":"google","system_fingerprint":null,"service_tier":"default","choices":[{"index":0,"logprobs":null,"finish_reason":"stop","native_finish_reason":"stop","message":{"role":"assistant","content":"positif","refusal":null,"reasoning":"**confirming positive sentiment**\\n\\nthe recent analysis confirms a strongly positive sentiment regarding the color, aligning perfectly with prior expectations. this aligns with my current assessment.\\n\\n","reasoning_details":[{"type":"reasoning.text","text":"**confirming positive sentiment**\\n\\nthe recent analysis confirms a strongly positive sentiment regarding the color, aligning perfectly with prior expectations. this aligns with my current assessment.\\n\\n","format":"google-gemini-v1","index":0}]}}],"usage":{"prompt_tokens":51,"completion_tokens":177,"total_tokens":228,"cost":0.000702,"is_byok":false,"prompt_tokens_details":{"cached_tokens":0,"cache_write_tokens":0,"audio_tokens":0,"video_tokens":0},"cost_details":{"upstream_inference_cost":0.000702,"upstream_inference_prompt_cost":0.00003825,"upstream_inference_completions_cost":0.00066375},"completion_tokens_details":{"reasoning_tokens":175,"image_tokens":0,"audio_tokens":0}}}',
 '{"id":"gen-1790397452-eniaeoz0rkrcwb5ul2nk","object":"chat.completion","created":1790397452,"model":"google/gemini-3.8-flash","provider":"google","system_fingerprint":null,"service_tier":"default","choices":[{"index":0,"logprobs":null,"finish_reason":"stop","native_finish_reason":"stop","message":{"role":"assistant","content":"positif","refusal":null,"reasoning":"**classifying sentiment quickly**\\n\\ni\'m focusing on rapid sentiment classification, aiming to distinguish between positive and negative reviews. my current task involves analyzing a review starting with \\"fast respon, peng\\".\\n\\n","reasoning_details":[{"type":"reasoning.text","text":"**classifying sentiment quickly**\\n\\ni\'m focusing on rapid sentiment classification, aiming to distinguish between positive and negative reviews. my current task involves analyzing a review starting with \\"fast respon, peng\\".\\n\\n","format":"google-gemini-v1","index":0}]}}],"usage":{"prompt_tokens":51,"completion_tokens":182,"total_tokens":233,"cost":0.00072075,"is_byok":false,"prompt_tokens_details":{"cached_tokens":0,"cache_write_tokens":0,"audio_tokens":0,"video_tokens":0},"cost_details":{"upstream_inference_cost":0.00072075,"upstream_inference_prompt_cost":0.00003825,"upstream_inference_completions_cost":0.0006825},"completion_tokens_details":{"reasoning_tokens":180,"image_tokens":0,"audio_tokens":0}}}',
 '{"id":"gen-1790397456-rttbjcqwr8nqj3fxxkmz","object":"chat.completion","created":1790397456,"model":"google/gemini-3.8-flash","provider":"google","system_fingerprint":null,"service_tier":"provisioned","choices":[{"index":0,"logprobs":null,"finish_reason":"stop","native_finish_reason":"stop","message":{"role":"assistant","content":"negatif","refusal":null,"reasoning":"**classifying the negative sentiment**\\n\\ni\'ve analyzed the provided text and it clearly expresses dissatisfaction. the statement \\"produk palsu, bukan barang original seperti yang dijanjikan\\" directly indicates that the product received was counterfeit and did not meet the advertised originality. therefore, i\'ve classified this as a negative sentiment.\\n\\n","reasoning_details":[{"type":"reasoning.text","text":"**classifying the negative sentiment**\\n\\ni\'ve analyzed the provided text and it clearly expresses dissatisfaction. the statement \\"produk palsu, bukan barang original seperti yang dijanjikan\\" directly indicates that the product received was counterfeit and did not meet the advertised originality. therefore, i\'ve classified this as a negative sentiment.\\n\\n","format":"google-gemini-v1","index":0}]}}],"usage":{"prompt_tokens":53,"completion_tokens":172,"total_tokens":225,"cost":0.00068475,"is_byok":false,"prompt_tokens_details":{"cached_tokens":0,"cache_write_tokens":0,"audio_tokens":0,"video_tokens":0},"cost_details":{"upstream_inference_cost":0.00068475,"upstream_inference_prompt_cost":0.00003975,"upstream_inference_completions_cost":0.000645},"completion_tokens_details":{"reasoning_tokens":170,"image_tokens":0,"audio_tokens":0}}}',
 '{"id":"gen-1790397461-pcmizl5h5npz7vzxxnxn","object":"chat.completion","created":1790397461,"model":"google/gemini-3.8-flash","provider":"google","system_fingerprint":null,"service_tier":"provisioned","choices":[{"index":0,"logprobs":null,"finish_reason":"stop","native_finish_reason":"stop","message":{"role":"assistant","content":"negatif","refusal":null,"reasoning":"**classifying sentiment:**\\n\\nmy current focus is on accurately assigning a sentiment of \\"positif\\" or \\"negatif\\" to incoming text. i am processing the input \\"komplain tidak ditangg\\" to determine its sentiment.\\n\\n","reasoning_details":[{"type":"reasoning.text","text":"**classifying sentiment:**\\n\\nmy current focus is on accurately assigning a sentiment of \\"positif\\" or \\"negatif\\" to incoming text. i am processing the input \\"komplain tidak ditangg\\" to determine its sentiment.\\n\\n","format":"google-gemini-v1","index":0}]}}],"usage":{"prompt_tokens":51,"completion_tokens":191,"total_tokens":242,"cost":0.0007545,"is_byok":false,"prompt_tokens_details":{"cached_tokens":0,"cache_write_tokens":0,"audio_tokens":0,"video_tokens":0},"cost_details":{"upstream_inference_cost":0.0007545,"upstream_inference_prompt_cost":0.00003825,"upstream_inference_completions_cost":0.00071625},"completion_tokens_details":{"reasoning_tokens":189,"image_tokens":0,"audio_tokens":0}}}',
 '{"id":"gen-1790397465-osluu9dazwrgqp9eitde","object":"chat.completion","created":1790397465,"model":"google/gemini-3.8-flash","provider":"google","system_fingerprint":null,"service_tier":"provisioned","choices":[{"index":0,"logprobs":null,"finish_reason":"stop","native_finish_reason":"stop","message":{"role":"assistant","content":"positif","refusal":null,"reasoning":"**classifying sentiment directly**\\n\\ni\'m focusing on a direct classification. the current review, \\"fast respon, pengiriman cepat, barang aman sampai tujuan,\\" clearly indicates satisfaction. therefore, the sentiment is unmistakably positive.\\n\\n","reasoning_details":[{"type":"reasoning.text","text":"**classifying sentiment directly**\\n\\ni\'m focusing on a direct classification. the current review, \\"fast respon, pengiriman cepat, barang aman sampai tujuan,\\" clearly indicates satisfaction. therefore, the sentiment is unmistakably positive.\\n\\n","format":"google-gemini-v1","index":0}]}}],"usage":{"prompt_tokens":51,"completion_tokens":168,"total_tokens":219,"cost":0.00066825,"is_byok":false,"prompt_tokens_details":{"cached_tokens":0,"cache_write_tokens":0,"audio_tokens":0,"video_tokens":0},"cost_details":{"upstream_inference_cost":0.00066825,"upstream_inference_prompt_cost":0.00003825,"upstream_inference_completions_cost":0.00063},"completion_tokens_details":{"reasoning_tokens":166,"image_tokens":0,"audio_tokens":0}}}',
 '{"id":"gen-1790397469-fssbclwcty5whb8u7b0h","object":"chat.completion","created":1790397469,"model":"google/gemini-3.8-flash","provider":"google","system_fingerprint":null,"service_tier":"provisioned","choices":[{"index":0,"logprobs":null,"finish_reason":"stop","native_finish_reason":"stop","message":{"role":"assistant","content":"negatif","refusal":null,"reasoning":"**classifying sentiment**\\n\\nmy analysis of the customer feedback \\"pengiriman lambat sekali, sudah dua minggu belum sampai\\" confirms a negative sentiment. the phrase directly conveys dissatisfaction with the delivery speed, leading to a clear classification.\\n\\n","reasoning_details":[{"type":"reasoning.text","text":"**classifying sentiment**\\n\\nmy analysis of the customer feedback \\"pengiriman lambat sekali, sudah dua minggu belum sampai\\" confirms a negative sentiment. the phrase directly conveys dissatisfaction with the delivery speed, leading to a clear classification.\\n\\n","format":"google-gemini-v1","index":0}]}}],"usage":{"prompt_tokens":51,"completion_tokens":183,"total_tokens":234,"cost":0.0007245,"is_byok":false,"prompt_tokens_details":{"cached_tokens":0,"cache_write_tokens":0,"audio_tokens":0,"video_tokens":0},"cost_details":{"upstream_inference_cost":0.0007245,"upstream_inference_prompt_cost":0.00003825,"upstream_inference_completions_cost":0.00068625},"completion_tokens_details":{"reasoning_tokens":181,"image_tokens":0,"audio_tokens":0}}}',
 '{"id":"gen-1790397473-3swq4wt6gqpniuk8gcny","object":"chat.completion","created":1790397473,"model":"google/gemini-3.8-flash","provider":"google","system_fingerprint":null,"service_tier":"provisioned","choices":[{"index":0,"logprobs":null,"finish_reason":"stop","native_finish_reason":"stop","message":{"role":"assistant","content":"positif","refusal":null,"reasoning":"**classifying sentiment accurately**\\n\\ni\'m focusing on the immediate task of determining sentiment. based on the provided text, \\"bahan nyaman dipakai, ukuran pas, tidak menge,\\" my current analysis points towards a positive sentiment.\\n\\n","reasoning_details":[{"type":"reasoning.text","text":"**classifying sentiment accurately**\\n\\ni\'m focusing on the immediate task of determining sentiment. based on the provided text, \\"bahan nyaman dipakai, ukuran pas, tidak menge,\\" my current analysis points towards a positive sentiment.\\n\\n","format":"google-gemini-v1","index":0}]}}],"usage":{"prompt_tokens":53,"completion_tokens":175,"total_tokens":228,"cost":0.000696,"is_byok":false,"prompt_tokens_details":{"cached_tokens":0,"cache_write_tokens":0,"audio_tokens":0,"video_tokens":0},"cost_details":{"upstream_inference_cost":0.000696,"upstream_inference_prompt_cost":0.00003975,"upstream_inference_completions_cost":0.00065625},"completion_tokens_details":{"reasoning_tokens":173,"image_tokens":0,"audio_tokens":0}}}',

### Sentimen Extraction from API Responses

In [74]:
y_pred_llm_clean = []
for pred in y_pred_llm:
    obj = json.loads(pred)
    content = obj["choices"][0]["message"]["content"]
    y_pred_llm_clean.append(content)
y_pred_llm_clean

['negatif',
 'positif',
 'positif',
 'positif',
 'negatif',
 'negatif',
 'positif',
 'positif',
 'negatif',
 'negatif',
 'positif',
 'negatif',
 'positif',
 'positif',
 'negatif',
 'positif',
 'negatif',
 'positif',
 'negatif',
 'negatif',
 'positif',
 'negatif',
 'positif',
 'positif',
 'positif',
 'positif',
 'positif',
 'positif',
 'positif',
 'negatif',
 'positif',
 'negatif',
 'positif',
 'negatif',
 'negatif',
 'negatif',
 'negatif',
 'negatif',
 'positif',
 'positif']

## 6. Evaluasi dan Perbandingan

### 6.1 Evaluasi Klasik

In [68]:
print('=== Model Klasik (Scikit-learn) ===')
print('Accuracy:', accuracy_score(y_test, y_pred_classic))
print(classification_report(y_test, y_pred_classic))
print('Confusion Matrix:\n', confusion_matrix(y_test, y_pred_classic))

=== Model Klasik (Scikit-learn) ===
Accuracy: 1.0
              precision    recall  f1-score   support

     negatif       1.00      1.00      1.00        18
     positif       1.00      1.00      1.00        22

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40

Confusion Matrix:
 [[18  0]
 [ 0 22]]

### 6.2 Evaluasi LLM

In [75]:
print('=== LLM API (Gemini) ===')
print('Accuracy:', accuracy_score(y_test, y_pred_llm_clean))
print(classification_report(y_test, y_pred_llm_clean))
print('Confusion Matrix:\n', confusion_matrix(y_test, y_pred_llm_clean))

=== LLM API (Gemini) ===
Accuracy: 1.0
              precision    recall  f1-score   support

     negatif       1.00      1.00      1.00        18
     positif       1.00      1.00      1.00        22

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40

Confusion Matrix:
 [[18  0]
 [ 0 22]]

### 6.3 Tabel Perbandingan

In [103]:
df_accuracy = pd.DataFrame([accuracy_score(y_test, y_pred_classic), accuracy_score(y_test, y_pred_llm_clean)], index=['Model Klasik', f'LLM API {model}'], columns=['Accuracy'])
df_classification_report_classic=pd.DataFrame(classification_report(y_test, y_pred_classic, output_dict=True)).T
df_classification_report_llm = pd.DataFrame(classification_report(y_test, y_pred_llm_clean, output_dict=True)).T
df_cm_classic= pd.DataFrame(confusion_matrix(y_test, y_pred_classic), index=['Negatif', 'Positif'], columns=['Negatif', 'Positif'])
df_cm_llm= pd.DataFrame(confusion_matrix(y_test, y_pred_llm_clean), index=['Negatif', 'Positif'], columns=['Negatif', 'Positif'])
display(df_accuracy)
print('==CLASSIFICATION REPORT==')
print('=== Model Klasik (Scikit-learn) ===')
display(df_classification_report_classic)
print('=== Confusion Matrix Model Klasik (Scikit-learn) ===')
display(df_cm_classic)
print(f'=== LLM API ({model}) ===')
display(df_classification_report_llm)
print(f'=== Confusion Matrix LLM API ({model}) ===')
display(df_cm_llm)

                                 Accuracy
Model Klasik                          1.0
LLM API google/gemini-3.8-flash       1.0

==CLASSIFICATION REPORT==
=== Model Klasik (Scikit-learn) ===

              precision  recall  f1-score  support
negatif             1.0     1.0       1.0     18.0
positif             1.0     1.0       1.0     22.0
accuracy            1.0     1.0       1.0      1.0
macro avg           1.0     1.0       1.0     40.0
weighted avg        1.0     1.0       1.0     40.0

=== Confusion Matrix Model Klasik (Scikit-learn) ===

         Negatif  Positif
Negatif       18        0
Positif        0       22

=== LLM API (google/gemini-3.8-flash) ===

              precision  recall  f1-score  support
negatif             1.0     1.0       1.0     18.0
positif             1.0     1.0       1.0     22.0
accuracy            1.0     1.0       1.0      1.0
macro avg           1.0     1.0       1.0     40.0
weighted avg        1.0     1.0       1.0     40.0

=== Confusion Matrix LLM API (google/gemini-3.8-flash) ===

         Negatif  Positif
Negatif       18        0
Positif        0       22

## 7. Analisis Trade Off dan Limitation

Menggunakan LLM dalam melakukan klasifikasi bisa dikatakan "Overshoot" karena menggunakan resource yang berlebihan, dilihat dari:
1. Kebutuhan API ke model LLM, perlu autentikasi dan coding API.
2. Membutuhkan Token.
3. Membutuhkan Prompting yang mengarahkan untuk membuat response hanya Positif atau Negatif.
4. Membutuhkan waktu pemerosesan lebih lama (2 Menitan).

## 8. Rekomendasi Technical Approach

Rekomendasi akhir untuk klasifikasi sentimen bisa menggunakan Metode Klasik dengan library sklearn yang lebih simple, dengan tingkat akurasi yang sama jika menggunakan API LLM (Resource lebih tinggi).